---
- include_vars: vars/was9_var.yml

- name: "Create components directories under {{SOFTWARE_REPOSITORY}}" 
  file:
    path: "{{SOFTWARE_REPOSITORY}}/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{ALL_COMPONENTS}}"
    
- name: "Create components directories under {{INSTALL_PARENT_DIR}}" 
  file:
    path: "{{INSTALL_PARENT_DIR}}/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{CREATE_DIR_DURING_INSTALL}}"
