---
- include_vars: vars/was9_var.yml

- name: "Profile creation"
  command: '"{{INSTALL_WAS9_DIR}}"/bin/manageprofiles.sh -create -templatePath  "{{INSTALL_WAS9_DIR}}"/profileTemplates/default -profileName {{item}} -ProfilePath  "{{INSTALL_WAS9_DIR}}"/profiles/{{item}}'
  args:
    chdir: "{{INSTALL_WAS9_DIR}}"
    creates: '"{{INSTALL_WAS9_DIR}}"/profiles/{{item}}'
  ignore_errors: yes
  with_items:
    - "{{PROFILES}}"

- name: "WAS console service start"
  command: '"{{INSTALL_WAS9_DIR}}"/profiles/{{item}}/bin/startServer.sh server1'
  ignore_errors: yes
  with_items:
    - "{{PROFILES}}"

