---
- include_vars: vars/db2_vars.yml

- name: "Create components directories under {{SOFTWARE_REPOSITORY}}" 
  file:
    path: "{{SOFTWARE_REPOSITORY}}/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{ALL_PRODUCTS}}"
    
- name: "Create components directories under {{INSTALL_PARENT_DIR}}" 
  file:
    path: "{{INSTALL_PARENT_DIR}}/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{CREATE_DIR_DURING_INSTALL}}"